apiVersion: v1
kind: ServiceAccount
metadata:
  name: argo-app-manager
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argo-app-manager-role
  namespace: default
rules:
  - apiGroups: ["argoproj.io"]
    resources: ["applications"]
    verbs: ["get", "list", "create", "update", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argo-app-manager-rolebinding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: argo-app-manager
    namespace: default
roleRef:
  kind: ClusterRole
  name: argo-app-manager-role
  apiGroup: rbac.authorization.k8s.io
